In [1]:
import numpy as np


* It creates numpy array



In [2]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

* It creates ones array 

In [3]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* I creates zeros array

In [4]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

* It fulls any variable what u entered and we can determine data type

In [5]:
np.full((2,2),5,dtype=float)

array([[5., 5.],
       [5., 5.]])

* It creates a numpy array from source to destination(What user enters)

In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

* It gives us intermediate variables of range 

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

* It takes any average and standart deviation and it creates variables depend on them

In [8]:
np.random.normal(10,4,(3,4))

array([[14.72779813,  4.98588457,  8.82988147,  5.60702581],
       [12.62820556, 14.85116377, 14.90266275,  8.50410474],
       [11.55129713, 12.45212767, 13.41540044,  6.8745423 ]])

* It takes range and creates random numbers 

In [9]:
np.random.randint(0,15,(3,3))

array([[ 4, 10, 12],
       [ 3,  9, 11],
       [ 3,  8,  5]])

* Map function  can perform in a vector,and it provides computing a significant functions

In [10]:
list1=[1,2,3,4,5]

list(map(lambda x:x*10,list1))

[10, 20, 30, 40, 50]

* The filter() function returns an iterator where the items are filtered through a function to test if the item is accepted or not.

In [11]:
list(filter(lambda x:x%2==0,list1))

[2, 4]

In [34]:
from functools import reduce
list2=[1,2,3,4]
reduce(lambda a,b:a + b,list2)

10

* **ndim:info. about dimension**
* **shape:inf. about row&column**
* **size:determines the size of numpy array**
* **dtype:gives data type of array**
* **reshape:resize the array**

In [13]:
a=np.random.randint(0,10,size=5)
a

array([6, 3, 1, 6, 4])

In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
a.dtype

dtype('int32')

In [17]:
b=np.random.randint(0,5,size=(3,5))
b

array([[1, 3, 3, 0, 2],
       [3, 4, 0, 4, 1],
       [0, 4, 4, 3, 2]])

In [18]:
b.ndim

2

In [19]:
b.shape

(3, 5)

In [20]:
b.dtype


dtype('int32')

In [21]:
a.reshape((1,5))

array([[6, 3, 1, 6, 4]])

* **Concatenate:It merges two array**
* **axis=0 for rows,**
* **axis=1 for columns.**

In [22]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [23]:
np.concatenate([a,a],axis=1)


array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

* **Split:splits the array as part**

In [24]:
x=np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y,z,t=np.split(x,[3,6])

In [26]:
y

array([1, 2, 3])

In [27]:
z

array([4, 5, 6])

In [36]:
t

array([7, 8, 9])

In [28]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* **np.vsplit:vertical splitting**

In [29]:
up,low=np.vsplit(m,[2])

In [30]:
up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
low

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* **np.hsplit:horizontal splitting**

In [38]:
left,right=np.hsplit(m,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [39]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

* **sort:sorts the array**

In [40]:
new=np.array([4,1,2,3,8,6,9])
a=np.sort(new)
a

array([1, 2, 3, 4, 6, 8, 9])

In [41]:
new

array([4, 1, 2, 3, 8, 6, 9])

* **There is difference between the functions because np.sort(new) does not affect the data**
* **the new.sort() changes order of the array.**

In [42]:
new.sort()
new

array([1, 2, 3, 4, 6, 8, 9])

In [43]:
new1=np.random.normal(20,3,(4,4))
new1

array([[22.5510515 , 21.08169984, 20.92226831, 16.78334168],
       [19.48522575, 17.10840231, 21.86631117, 24.76556542],
       [20.65118913, 21.89995861, 19.85443833, 22.98367187],
       [20.33780961, 23.81923742, 19.59850608, 24.70793719]])

In [44]:
np.sort(new1,axis=0) #Sorting Rows

array([[19.48522575, 17.10840231, 19.59850608, 16.78334168],
       [20.33780961, 21.08169984, 19.85443833, 22.98367187],
       [20.65118913, 21.89995861, 20.92226831, 24.70793719],
       [22.5510515 , 23.81923742, 21.86631117, 24.76556542]])

In [45]:
np.sort(new1,axis=1) #Sorting Columns

array([[16.78334168, 20.92226831, 21.08169984, 22.5510515 ],
       [17.10840231, 19.48522575, 21.86631117, 24.76556542],
       [19.85443833, 20.65118913, 21.89995861, 22.98367187],
       [19.59850608, 20.33780961, 23.81923742, 24.70793719]])

In [46]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [ ]:
a=np.random.randint(10,size=(3,5))
a

In [ ]:
a[0,1] #Accessing variables with indexes.row,column

* **_Slicing_**

In [47]:
b=np.random.randint(20,size=10)
b.sort()
b[0:5]


array([ 0,  1,  5,  8, 13])

* **_This method is leaping by 2_**

In [48]:
b[:10:2]

array([ 0,  5, 13, 14, 18])

* **_Two dimensional (All rows,decided column)_**

In [52]:
m=np.random.randint(20,size=(5,5))
m

array([[10,  4, 16,  1, 19],
       [ 8, 14, 12, 12, 18],
       [15, 11,  0,  6, 11],
       [ 2, 15, 12, 14,  1],
       [ 6,  5, 12,  6,  9]])

In [53]:
m[:,3]

array([ 1, 12,  6, 14,  6])

* **_All columns,decided row_**

In [54]:
m[2,:]

array([15, 11,  0,  6, 11])

* **_Specific rows and columns_**

In [55]:
m[2,1]

11

In [57]:
m[0,4]

19

In [58]:
m[:,:2]

array([[10,  4],
       [ 8, 14],
       [15, 11],
       [ 2, 15],
       [ 6,  5]])

In [59]:
m[1:3,:3]

array([[ 8, 14, 12],
       [15, 11,  0]])

In [60]:
m[:2,:]

array([[10,  4, 16,  1, 19],
       [ 8, 14, 12, 12, 18]])

 * **_If you want to apply any solution in subset you should use .copy()_**

In [63]:
n=m[:2,:].copy()   #if we dont use copy method our original
                    #array will chance
n[0,1]=13
n

array([[10, 13, 16,  1, 19],
       [ 8, 14, 12, 12, 18]])

In [65]:
c=np.arange(0,30,3)
c

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

* **_Calling Multiple Indexes(Fancy İndex).Pairing row to row and column by column._**

In [66]:
bring=[1,3,5,7]
c[bring]

array([ 3,  9, 15, 21])

In [67]:
z=np.arange(1,27,3).reshape(3,3)

row=np.array([1,2])
column=np.array([1,2])
z


array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [68]:
z[row,column]


array([13, 25])

In [69]:
z[1,1]

13

In [70]:
z[0:,[1,2]]

array([[ 4,  7],
       [13, 16],
       [22, 25]])

In [73]:
z[z>5]

array([ 7, 10, 13, 16, 19, 22, 25])

In [74]:
z[z>=5]

array([ 7, 10, 13, 16, 19, 22, 25])

In [75]:
z[z==5]

array([], dtype=int32)

In [76]:
z[z!=5]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

* **_Mathematical Calculations_**

In [77]:
z

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [78]:
z+2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [79]:
z*2

array([[ 2,  8, 14],
       [20, 26, 32],
       [38, 44, 50]])

In [80]:
z-2

array([[-1,  2,  5],
       [ 8, 11, 14],
       [17, 20, 23]])

In [81]:
z/2

array([[ 0.5,  2. ,  3.5],
       [ 5. ,  6.5,  8. ],
       [ 9.5, 11. , 12.5]])

In [82]:
np.multiply(z,4)

array([[  4,  16,  28],
       [ 40,  52,  64],
       [ 76,  88, 100]])

In [83]:
np.add(z,2)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [84]:
np.subtract(z,2)

array([[-1,  2,  5],
       [ 8, 11, 14],
       [17, 20, 23]])

In [85]:
np.divide(z,3)

array([[0.33333333, 1.33333333, 2.33333333],
       [3.33333333, 4.33333333, 5.33333333],
       [6.33333333, 7.33333333, 8.33333333]])

In [86]:
np.power(z,3)

array([[    1,    64,   343],
       [ 1000,  2197,  4096],
       [ 6859, 10648, 15625]], dtype=int32)

In [87]:
np.mod(z,2)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [88]:
np.absolute(np.array([-2]))

array([2])

In [89]:
np.cos(0)

1.0

In [90]:
np.sin(360)

0.9589157234143065

In [91]:
np.log(z)

array([[0.        , 1.38629436, 1.94591015],
       [2.30258509, 2.56494936, 2.77258872],
       [2.94443898, 3.09104245, 3.21887582]])

In [92]:
np.log2(z)

array([[0.        , 2.        , 2.80735492],
       [3.32192809, 3.70043972, 4.        ],
       [4.24792751, 4.45943162, 4.64385619]])

In [93]:
?np

* **_Liner Algebra_**

In [95]:
a=np.array([[3,2],[5,1]])
b=np.array([10,5])

x=np.linalg.solve(a,b)
x

array([0., 5.])

* **_Practisesssssssss_**


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[1,2,3,4]],dtype=int)
a

In [ ]:
b=np.arange(0,30,3).reshape(5,2)
b

In [ ]:
np.ones((3,5),dtype=int)

In [ ]:
np.zeros((3,5),dtype=int)

In [ ]:
np.full((3,5),5,dtype=int)

In [ ]:
np.linspace(0,100,10,dtype=int)

In [ ]:
np.random.normal(20,5,(3,5))

In [ ]:
np.random.randint(0,10,(3,3))

In [ ]:
a=np.arange(0,10,2)
a

In [ ]:
b=list(map(lambda x:x*10,a))
b

In [ ]:
list(filter(lambda x:x==2,a))

In [ ]:
from functools import reduce 
reduce(lambda c,b:c+b,a)

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
a.size

In [ ]:
a.reshape(5,1)

In [ ]:
b=np.array([[1,2,3,4,5],[5,6,7,8,9]])
b.reshape(2,5)

In [ ]:
b.ndim

In [ ]:
np.concatenate((b,b),axis=1)

In [ ]:
b

In [ ]:
x,y=np.hsplit(b,[2])
x